/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xdev_gmdev_GM_UID */

#ifndef _Included_xdev_gmdev_GM_UID
#define _Included_xdev_gmdev_GM_UID
#ifdef __cplusplus
extern "C" {
#endif
#undef xdev_gmdev_GM_UID__SIZE
#define xdev_gmdev_GM_UID__SIZE 0L
#ifdef __cplusplus
}
#endif
#endif
