/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xdev_gmdev_GM_HPort */

#ifndef _Included_xdev_gmdev_GM_HPort
#define _Included_xdev_gmdev_GM_HPort
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
