/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xdev_gmdev_PinTest */

#ifndef _Included_xdev_gmdev_PinTest
#define _Included_xdev_gmdev_PinTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xdev_gmdev_PinTest
 * Method:    pinIt
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_xdev_gmdev_PinTest_pinIt___3B
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     xdev_gmdev_PinTest
 * Method:    pinIt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xdev_gmdev_PinTest_pinIt__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
