/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpjdev_natmpjdev_Win_LocalSyncManager */

#ifndef _Included_mpjdev_natmpjdev_Win_LocalSyncManager
#define _Included_mpjdev_natmpjdev_Win_LocalSyncManager
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
