/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpjdev_natmpjdev_NativeCollRequest */

#ifndef _Included_mpjdev_natmpjdev_NativeCollRequest
#define _Included_mpjdev_natmpjdev_NativeCollRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpjdev_natmpjdev_NativeCollRequest
 * Method:    initNativeCollRequest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_NativeCollRequest_initNativeCollRequest
  (JNIEnv *, jclass);

/*
 * Class:     mpjdev_natmpjdev_NativeCollRequest
 * Method:    Wait
 * Signature: (Lmpjdev/Status;)Lmpjdev/Status;
 */
JNIEXPORT jobject JNICALL Java_mpjdev_natmpjdev_NativeCollRequest_Wait
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mpjdev_natmpjdev_NativeCollRequest
 * Method:    Test
 * Signature: (Lmpjdev/Status;)Lmpjdev/Status;
 */
JNIEXPORT jobject JNICALL Java_mpjdev_natmpjdev_NativeCollRequest_Test
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
